title: NSW Mesh Wiki

# GitHub Pages will automatically use the minima theme
theme: minima

# Jekyll serves from root, content lives in root and docs/

# Basic plugins that GitHub Pages supports
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude README.md so index.md takes precedence
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# Footer content
author: NSW Mesh Community
email:
description: Community-maintained knowledge base for everything Meshtastic in Sydney and throughout New South Wales
